import { useMemo } from "react";
import { AlertTriangle, CheckCircle2, Clock3, ListChecks, Target } from "lucide-react";
import { calculateDeliveryMetrics } from "@/lib/deliveryMetrics";

function formatRate(rate) { return rate == null ? "—" : `${rate}%`; }
function formatDate(value) { if (!value) return "—"; const [year, month, day] = value.slice(0, 10).split("-"); return `${day}/${month}/${year}`; }
function Card({ icon: Icon, label, value, detail, color }) { return <div className="glass-card p-4"><div className="flex items-center gap-3"><div className={`flex h-9 w-9 items-center justify-center rounded-xl ${color}`}><Icon className="h-4 w-4" /></div><div><p className="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">{label}</p><p className="text-2xl font-black text-foreground">{value}</p></div></div><p className="mt-2 text-xs text-muted-foreground">{detail}</p></div>; }

export default function DeliveryReport({ jobs = [], subtasks = [], collaborators = [], clients = [], period, responsibleId = "", stage = "" }) {
  const metrics = useMemo(() => calculateDeliveryMetrics({ jobs, subtasks, collaborators, clients, period }), [jobs, subtasks, collaborators, clients, period]);
  const responsibleName = collaborators.find((collaborator) => collaborator.id === responsibleId)?.name || responsibleId;
  const normalizedStage = stage.trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
  const detailRows = metrics.detailRows.filter((row) => {
    if (responsibleId && row.responsibleId !== responsibleId) return false;
    if (normalizedStage && !row.taskTitle.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").includes(normalizedStage)) return false;
    return true;
  });
  return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Card icon={AlertTriangle} label="Jobs atrasados" value={metrics.totals.overdueJobs} detail="Pela data de postagem" color="bg-red-50 text-red-600" /><Card icon={ListChecks} label="Tarefas atrasadas" value={metrics.totals.overdueTasks} detail="Etapas abertas fora do prazo" color="bg-amber-50 text-amber-600" /><Card icon={CheckCircle2} label="Entregas no prazo" value={formatRate(metrics.totals.onTimeRate)} detail={`${metrics.totals.onTimeTasks} concluídas dentro do prazo`} color="bg-emerald-50 text-emerald-600" /><Card icon={Clock3} label="Próximos 5 dias" value={metrics.totals.upcomingNotScheduled} detail="Postagens não agendadas" color="bg-primary/10 text-primary" /></div>
    {(responsibleName || stage) && <div className="rounded-xl border border-primary/20 bg-primary/5 px-4 py-3 text-xs text-primary">Detalhamento filtrado{responsibleName ? ` por ${responsibleName}` : ""}{stage ? ` · etapa: ${stage}` : ""}. Os indicadores acima continuam mostrando o período completo.</div>}
    <div className="glass-card overflow-hidden"><div className="flex items-center justify-between border-b border-border px-5 py-4"><div><h3 className="font-semibold text-foreground">Desempenho por responsável</h3><p className="text-xs text-muted-foreground">Tarefas concluídas entre {formatDate(metrics.period.start)} e {formatDate(metrics.period.end)}</p></div><Target className="h-5 w-5 text-primary" /></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-border text-left text-xs text-muted-foreground"><th className="px-5 py-3">Responsável</th><th className="px-3 py-3 text-center">Jobs atrasados</th><th className="px-3 py-3 text-center">Tarefas atrasadas</th><th className="px-3 py-3 text-center">Entregues</th><th className="px-3 py-3 text-center">No prazo</th><th className="px-5 py-3 text-center">Índice</th></tr></thead><tbody>{metrics.responsibleRows.length === 0 ? <tr><td colSpan="6" className="px-5 py-10 text-center text-muted-foreground">Nenhuma entrega encontrada no período.</td></tr> : metrics.responsibleRows.map((row) => <tr key={row.id} className="border-b border-border/70 last:border-0"><td className="px-5 py-3 font-medium text-foreground">{row.name}</td><td className="px-3 py-3 text-center font-semibold text-red-600">{row.overdueJobs}</td><td className="px-3 py-3 text-center font-semibold text-amber-600">{row.overdueTasks}</td><td className="px-3 py-3 text-center text-foreground">{row.completedTasks}</td><td className="px-3 py-3 text-center text-emerald-600">{row.onTimeTasks}</td><td className="px-5 py-3 text-center font-bold text-foreground">{formatRate(row.onTimeRate)}</td></tr>)}</tbody></table></div></div>
    <div className="grid gap-5 lg:grid-cols-2"><div className="glass-card overflow-hidden"><div className="border-b border-border px-5 py-4"><h3 className="font-semibold text-foreground">Atrasos por etapa</h3><p className="text-xs text-muted-foreground">Etapa atual e responsável da tarefa</p></div><div className="divide-y divide-border">{metrics.stageRows.length === 0 ? <p className="p-5 text-center text-xs text-muted-foreground">Nenhum atraso por etapa.</p> : metrics.stageRows.map((row) => <div key={row.key} className="flex items-center justify-between gap-3 px-5 py-3"><div className="min-w-0"><p className="truncate text-sm font-medium text-foreground">{row.stage}</p><p className="truncate text-xs text-muted-foreground">{row.responsibleName}</p></div><div className="shrink-0 text-right"><p className="text-sm font-bold text-red-600">{row.jobs} jobs</p><p className="text-[10px] text-muted-foreground">mais antigo: {formatDate(row.oldestPostDate)}</p></div></div>)}</div></div><div className="glass-card overflow-hidden"><div className="border-b border-border px-5 py-4"><h3 className="font-semibold text-foreground">Atrasos por cliente</h3><p className="text-xs text-muted-foreground">Concentração dos jobs com postagem vencida</p></div><div className="divide-y divide-border">{metrics.clientRows.length === 0 ? <p className="p-5 text-center text-xs text-muted-foreground">Nenhum cliente com atraso.</p> : metrics.clientRows.map((row) => <div key={row.id} className="flex items-center justify-between px-5 py-3"><span className="text-sm font-medium text-foreground">{row.name}</span><span className="text-xs text-muted-foreground">{row.jobs} jobs · {row.tasks} tarefas</span></div>)}</div></div></div>
    <div className="glass-card overflow-hidden"><div className="border-b border-border px-5 py-4"><h3 className="font-semibold text-foreground">Detalhamento das entregas</h3><p className="text-xs text-muted-foreground">Cliente · job · tarefa · data · responsável · situação</p></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b border-border text-left text-xs text-muted-foreground"><th className="px-5 py-3">Cliente</th><th className="px-3 py-3">Job</th><th className="px-3 py-3">Tarefa/etapa</th><th className="px-3 py-3">Data</th><th className="px-3 py-3">Responsável</th><th className="px-3 py-3">Situação</th></tr></thead><tbody>{detailRows.length === 0 ? <tr><td colSpan="6" className="px-5 py-10 text-center text-muted-foreground">Nenhum registro encontrado no período e filtro selecionados.</td></tr> : detailRows.map((row) => <tr key={row.key} className="border-b border-border/70 last:border-0"><td className="px-5 py-3 font-medium text-foreground">{row.clientName}</td><td className="px-3 py-3 text-foreground">{row.jobTitle}</td><td className="px-3 py-3 text-foreground">{row.taskTitle}</td><td className="px-3 py-3 whitespace-nowrap text-muted-foreground">{formatDate(row.date)}</td><td className="px-3 py-3 text-muted-foreground">{row.responsibleName}</td><td className="px-3 py-3"><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${row.kind === "Entregue no prazo" ? "bg-emerald-100 text-emerald-700" : row.kind === "Entregue fora do prazo" ? "bg-orange-100 text-orange-700" : "bg-red-100 text-red-700"}`}>{row.kind}</span></td></tr>)}</tbody></table></div></div>
  </div>;
}
