import { useMemo } from "react";
import { AlertTriangle, ArrowRight, CheckCircle2, Clock3, ListChecks, Target } from "lucide-react";
import { createPageUrl } from "@/utils";
import { calculateDeliveryMetrics } from "@/lib/deliveryMetrics";

function formatRate(rate) { return rate == null ? "—" : `${rate}%`; }

function Metric({ icon: Icon, label, value, detail, tone = "blue" }) {
  const tones = { red: "bg-red-50 text-red-600 dark:bg-red-950/20", amber: "bg-amber-50 text-amber-600 dark:bg-amber-950/20", green: "bg-emerald-50 text-emerald-600 dark:bg-emerald-950/20", blue: "bg-primary/10 text-primary" };
  return <div className="rounded-xl border border-border bg-background/60 p-3"><div className="flex items-center gap-2"><div className={`flex h-8 w-8 items-center justify-center rounded-lg ${tones[tone]}`}><Icon className="h-4 w-4" /></div><div className="min-w-0"><p className="truncate text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">{label}</p><p className="text-xl font-black text-foreground">{value}</p></div></div><p className="mt-2 text-[10px] text-muted-foreground">{detail}</p></div>;
}

export default function DeliveryMetricsWidget({ jobs = [], subtasks = [], collaborators = [], clients = [], todayStr }) {
  const metrics = useMemo(() => calculateDeliveryMetrics({ jobs, subtasks, collaborators, clients, today: todayStr }), [jobs, subtasks, collaborators, clients, todayStr]);
  const topResponsible = metrics.responsibleRows.slice(0, 8);
  const topStages = metrics.stageRows.slice(0, 8);

  return <section className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm">
    <div className="flex flex-col gap-2 border-b border-border px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-primary/10 text-primary"><Target className="h-5 w-5" /></div><div><h3 className="text-sm font-bold text-foreground">Gestão de entregas</h3><p className="text-xs text-muted-foreground">Data de postagem, etapa e responsável · mês atual</p></div></div><a href={`${createPageUrl("Reports")}?section=jobs&report=delivery`} className="flex items-center gap-1 text-xs font-semibold text-primary no-underline hover:underline">Ver relatório <ArrowRight className="h-3.5 w-3.5" /></a></div>
    <div className="grid gap-3 p-5 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={AlertTriangle} label="Jobs atrasados" value={metrics.totals.overdueJobs} detail={`${metrics.totals.activeJobs} jobs ativos no total`} tone={metrics.totals.overdueJobs ? "red" : "green"} /><Metric icon={ListChecks} label="Tarefas atrasadas" value={metrics.totals.overdueTasks} detail={`${metrics.totals.activeTasks} tarefas abertas`} tone={metrics.totals.overdueTasks ? "amber" : "green"} /><Metric icon={CheckCircle2} label="Entregas no prazo" value={formatRate(metrics.totals.onTimeRate)} detail={`${metrics.totals.onTimeTasks} de ${metrics.totals.completedTasks} tarefas com prazo`} tone="green" /><Metric icon={Clock3} label="Próximos 5 dias" value={metrics.totals.upcomingNotScheduled} detail="postagens ativas ainda não agendadas" tone={metrics.totals.upcomingNotScheduled ? "amber" : "blue"} /></div>
    <div className="grid gap-5 border-t border-border p-5 lg:grid-cols-2"><div><div className="mb-3 flex items-center justify-between"><h4 className="text-xs font-bold text-foreground">Atrasos por responsável</h4><span className="text-[10px] text-muted-foreground">jobs · tarefas · no prazo</span></div>{topResponsible.length === 0 ? <p className="rounded-xl border border-dashed border-border p-5 text-center text-xs text-muted-foreground">Nenhum dado de entrega no período.</p> : <div className="space-y-1.5">{topResponsible.map((row) => <div key={row.id} className="flex items-center justify-between gap-3 rounded-xl border border-border px-3 py-2.5"><span className="truncate text-xs font-semibold text-foreground">{row.name}</span><div className="flex shrink-0 items-center gap-2 text-[10px] font-semibold"><span className="text-red-600">{row.overdueJobs} jobs</span><span className="text-amber-600">{row.overdueTasks} tarefas</span><span className="text-emerald-600">{formatRate(row.onTimeRate)}</span></div></div>)}</div>}</div><div><div className="mb-3 flex items-center justify-between"><h4 className="text-xs font-bold text-foreground">Atrasos por etapa</h4><span className="text-[10px] text-muted-foreground">responsável atual</span></div>{topStages.length === 0 ? <p className="rounded-xl border border-dashed border-border p-5 text-center text-xs text-muted-foreground">Nenhuma etapa atrasada.</p> : <div className="space-y-1.5">{topStages.map((row) => <div key={row.key} className="flex items-center justify-between gap-3 rounded-xl border border-border px-3 py-2.5"><div className="min-w-0"><p className="truncate text-xs font-semibold text-foreground">{row.stage}</p><p className="truncate text-[10px] text-muted-foreground">{row.responsibleName}</p></div><div className="shrink-0 text-right"><p className="text-xs font-bold text-red-600">{row.jobs} jobs</p><p className="text-[10px] text-muted-foreground">{row.ageDays}d de atraso</p></div></div>)}</div>}</div></div>
  </section>;
}
