-- Observabilidade de compatibilidade durante a migração.

create or replace view public.maestro_dual_write_health as
select * from (
  select 'Client'::text as entity, (select count(*) from public.legacy_records where entity='Client')::bigint as legacy_count, (select count(*) from public.maestro_clients)::bigint as relational_count, (select count(*) from public.maestro_clients r join public.legacy_records l on l.entity='Client' and l.record_id=r.legacy_record_id where r.source_payload is distinct from l.payload)::bigint as payload_mismatches
  union all select 'Project', (select count(*) from public.legacy_records where entity='Project'), (select count(*) from public.maestro_projects), (select count(*) from public.maestro_projects r join public.legacy_records l on l.entity='Project' and l.record_id=r.legacy_record_id where r.source_payload is distinct from l.payload)
  union all select 'Job', (select count(*) from public.legacy_records where entity='Job'), (select count(*) from public.maestro_jobs), (select count(*) from public.maestro_jobs r join public.legacy_records l on l.entity='Job' and l.record_id=r.legacy_record_id where r.source_payload is distinct from l.payload)
  union all select 'FinancialEntry', (select count(*) from public.legacy_records where entity='FinancialEntry'), (select count(*) from public.maestro_financial_entries), (select count(*) from public.maestro_financial_entries r join public.legacy_records l on l.entity='FinancialEntry' and l.record_id=r.legacy_record_id where r.source_payload is distinct from l.payload)
  union all select 'WhatsappContact', (select count(*) from public.legacy_records where entity='WhatsappContact'), (select count(*) from public.maestro_whatsapp_contacts), (select count(*) from public.maestro_whatsapp_contacts r join public.legacy_records l on l.entity='WhatsappContact' and l.record_id=r.legacy_record_id where r.payload is distinct from l.payload)
  union all select 'WhatsappGroup', (select count(*) from public.legacy_records where entity='WhatsappGroup'), (select count(*) from public.maestro_whatsapp_groups), (select count(*) from public.maestro_whatsapp_groups r join public.legacy_records l on l.entity='WhatsappGroup' and l.record_id=r.legacy_record_id where r.payload is distinct from l.payload)
  union all select 'NpsHistory', (select count(*) from public.legacy_records where entity='NpsHistory'), (select count(*) from public.maestro_nps_history), (select count(*) from public.maestro_nps_history r join public.legacy_records l on l.entity='NpsHistory' and l.record_id=r.legacy_record_id where r.payload is distinct from l.payload)
  union all select 'Comment', (select count(*) from public.legacy_records where entity='Comment' and coalesce(payload->>'entity_type','job')='job'), (select count(*) from public.maestro_job_comments), (select count(*) from public.maestro_job_comments r join public.legacy_records l on l.entity='Comment' and l.record_id=r.legacy_record_id where r.payload is distinct from l.payload)
  union all select 'DominusWebhookParsed', (select count(*) from public.legacy_records where entity='DominusWebhookParsed'), (select count(*) from public.maestro_webhook_parsed_messages), (select count(*) from public.maestro_webhook_parsed_messages r join public.legacy_records l on l.entity='DominusWebhookParsed' and l.record_id=r.legacy_record_id where r.payload is distinct from l.payload)
  union all select 'MiniTask', (select count(*) from public.legacy_records where entity='MiniTask'), (select count(*) from public.maestro_mini_tasks), (select count(*) from public.maestro_mini_tasks r join public.legacy_records l on l.entity='MiniTask' and l.record_id=r.legacy_record_id where r.task_payload is distinct from l.payload)
) health;

comment on view public.maestro_dual_write_health is 'Indicadores de paridade entre legacy_records e tabelas relacionais durante a migração.';
revoke all on public.maestro_dual_write_health from anon, authenticated;
grant select on public.maestro_dual_write_health to service_role;
