create or replace view public.maestro_legacy_cutover_health as
with parity as (
  select 'Client' entity, (select count(*) from public.legacy_records where entity='Client') legacy_count, (select count(*) from public.maestro_clients) relational_count, (select count(*) from public.maestro_clients r join public.legacy_records l on l.entity='Client' and l.record_id=r.legacy_record_id where r.source_payload is distinct from l.payload) payload_mismatches
  union all select 'Project', (select count(*) from public.legacy_records where entity='Project'), (select count(*) from public.maestro_projects), (select count(*) from public.maestro_projects r join public.legacy_records l on l.entity='Project' and l.record_id=r.legacy_record_id where r.source_payload is distinct from l.payload)
  union all select 'Job', (select count(*) from public.legacy_records where entity='Job'), (select count(*) from public.maestro_jobs), (select count(*) from public.maestro_jobs r join public.legacy_records l on l.entity='Job' and l.record_id=r.legacy_record_id where r.source_payload is distinct from l.payload)
  union all select 'Subtask', (select count(*) from public.legacy_records where entity='Subtask'), (select count(*) from public.maestro_job_tasks), (select count(*) from public.maestro_job_tasks r join public.legacy_records l on l.entity='Subtask' and l.record_id=r.legacy_record_id where r.source_payload is distinct from l.payload)
  union all select 'FinancialEntry', (select count(*) from public.legacy_records where entity='FinancialEntry'), (select count(*) from public.maestro_financial_entries), (select count(*) from public.maestro_financial_entries r join public.legacy_records l on l.entity='FinancialEntry' and l.record_id=r.legacy_record_id where r.source_payload is distinct from l.payload)
  union all select 'AgendaEvent', (select count(*) from public.legacy_records where entity='AgendaEvent'), (select count(*) from public.maestro_agenda_events), (select count(*) from public.maestro_agenda_events r join public.legacy_records l on l.entity='AgendaEvent' and l.record_id=r.legacy_record_id where r.source_payload is distinct from l.payload)
  union all select 'Timesheet', (select count(*) from public.legacy_records where entity='Timesheet'), (select count(*) from public.maestro_timesheets), (select count(*) from public.maestro_timesheets r join public.legacy_records l on l.entity='Timesheet' and l.record_id=r.legacy_record_id where r.source_payload is distinct from l.payload)
  union all select 'Notification', (select count(*) from public.legacy_records where entity='Notification'), (select count(*) from public.maestro_notifications), (select count(*) from public.maestro_notifications r join public.legacy_records l on l.entity='Notification' and l.record_id=r.legacy_record_id where r.source_payload is distinct from l.payload)
  union all select 'BankAccount', (select count(*) from public.legacy_records where entity='BankAccount'), (select count(*) from public.maestro_bank_accounts), (select count(*) from public.maestro_bank_accounts r join public.legacy_records l on l.entity='BankAccount' and l.record_id=r.legacy_record_id where r.payload is distinct from l.payload)
  union all select 'FinancialCategory', (select count(*) from public.legacy_records where entity='FinancialCategory'), (select count(*) from public.maestro_financial_categories), (select count(*) from public.maestro_financial_categories r join public.legacy_records l on l.entity='FinancialCategory' and l.record_id=r.legacy_record_id where r.payload is distinct from l.payload)
  union all select 'CostCenter', (select count(*) from public.legacy_records where entity='CostCenter'), (select count(*) from public.maestro_cost_centers), (select count(*) from public.maestro_cost_centers r join public.legacy_records l on l.entity='CostCenter' and l.record_id=r.legacy_record_id where r.payload is distinct from l.payload)
  union all select 'JobTemplate', (select count(*) from public.legacy_records where entity='JobTemplate'), (select count(*) from public.maestro_job_templates), (select count(*) from public.maestro_job_templates r join public.legacy_records l on l.entity='JobTemplate' and l.record_id=r.legacy_record_id where r.template_payload is distinct from l.payload)
  union all select 'Proposal', (select count(*) from public.legacy_records where entity='Proposal'), (select count(*) from public.maestro_proposals), (select count(*) from public.maestro_proposals r join public.legacy_records l on l.entity='Proposal' and l.record_id=r.legacy_record_id where r.proposal_payload is distinct from l.payload)
  union all select 'Note', (select count(*) from public.legacy_records where entity='Note'), (select count(*) from public.maestro_notes), (select count(*) from public.maestro_notes r join public.legacy_records l on l.entity='Note' and l.record_id=r.legacy_record_id where r.note_payload is distinct from l.payload)
  union all select 'WhatsappContact', (select count(*) from public.legacy_records where entity='WhatsappContact'), (select count(*) from public.maestro_whatsapp_contacts), (select count(*) from public.maestro_whatsapp_contacts r join public.legacy_records l on l.entity='WhatsappContact' and l.record_id=r.legacy_record_id where r.payload is distinct from l.payload)
  union all select 'WhatsappGroup', (select count(*) from public.legacy_records where entity='WhatsappGroup'), (select count(*) from public.maestro_whatsapp_groups), (select count(*) from public.maestro_whatsapp_groups r join public.legacy_records l on l.entity='WhatsappGroup' and l.record_id=r.legacy_record_id where r.payload is distinct from l.payload)
  union all select 'NpsEntry', (select count(*) from public.legacy_records where entity='NpsEntry'), (select count(*) from public.maestro_nps_entries), (select count(*) from public.maestro_nps_entries r join public.legacy_records l on l.entity='NpsEntry' and l.record_id=r.legacy_record_id where r.payload is distinct from l.payload)
  union all select 'NpsHistory', (select count(*) from public.legacy_records where entity='NpsHistory'), (select count(*) from public.maestro_nps_history), (select count(*) from public.maestro_nps_history r join public.legacy_records l on l.entity='NpsHistory' and l.record_id=r.legacy_record_id where r.payload is distinct from l.payload)
  union all select 'Comment', (select count(*) from public.legacy_records where entity='Comment' and coalesce(payload->>'entity_type','job')='job'), (select count(*) from public.maestro_job_comments), (select count(*) from public.maestro_job_comments r join public.legacy_records l on l.entity='Comment' and l.record_id=r.legacy_record_id where r.payload is distinct from l.payload)
  union all select 'DominusWebhookParsed', (select count(*) from public.legacy_records where entity='DominusWebhookParsed'), (select count(*) from public.maestro_webhook_parsed_messages), (select count(*) from public.maestro_webhook_parsed_messages r join public.legacy_records l on l.entity='DominusWebhookParsed' and l.record_id=r.legacy_record_id where r.payload is distinct from l.payload)
  union all select 'WhatsappAutomation', (select count(*) from public.legacy_records where entity='WhatsappAutomation'), (select count(*) from public.maestro_whatsapp_automations), (select count(*) from public.maestro_whatsapp_automations r join public.legacy_records l on l.entity='WhatsappAutomation' and l.record_id=r.legacy_record_id where r.automation_payload is distinct from l.payload)
)
select r.entity, r.module_key, r.status, r.read_mode, r.write_mode, r.legacy_read_allowed, r.legacy_write_allowed,
  p.legacy_count, p.relational_count, p.payload_mismatches,
  case when p.payload_mismatches <> 0 or p.legacy_count <> p.relational_count then 'diverged'
       when r.status in ('frozen','retired') and r.legacy_write_allowed then 'invalid_cutover'
       else 'ok' end as health_status
from public.legacy_cutover_registry r
left join parity p on p.entity=r.entity;

revoke all on public.maestro_legacy_cutover_health from anon, authenticated;
grant select on public.maestro_legacy_cutover_health to service_role;
